################################
# ACQUISITION for 1 projection #
################################
/gate/application/setTimeSlice     20000. s
/gate/application/setTimeStart     0.  s
/gate/application/setTimeStop      20000. s

####################################
# ACQUISITION with 360 projections #
####################################
#/gate/application/setTimeSlice     1. s
#/gate/application/setTimeStart     0.  s
#/gate/application/setTimeStop      360. s

/gate/application/startDAQ

