##################
# Water Cylinder #
##################
/gate/world/daughters/name waterBox
/gate/world/daughters/insert box
/gate/waterBox/geometry/setXLength 15 mm
/gate/waterBox/geometry/setXLength 70 mm
/gate/waterBox/geometry/setXLength 70 mm
/gate/waterBox/setMaterial Water
/gate/waterBox/vis/forceWireframe
/gate/waterBox/vis/setColor cyan


##################################
# Bone, Cortical (ICRU-44) Balls #
##################################
/gate/waterBox/daughters/name boneBall1
/gate/waterBox/daughters/insert sphere
/gate/boneBall1/placement/setTranslation 0. -20 -25 mm
/gate/boneBall1/geometry/setRmin 0. mm
/gate/boneBall1/geometry/setRmax 2. mm
/gate/boneBall1/setMaterial Bone_Cortical_ICRU_44
/gate/boneBall1/vis/setColor white

/gate/waterBox/daughters/name boneBall2
/gate/waterBox/daughters/insert sphere
/gate/boneBall2/placement/setTranslation 0. 0. -25 mm
/gate/boneBall2/geometry/setRmin 0. mm
/gate/boneBall2/geometry/setRmax 3.5 mm
/gate/boneBall2/setMaterial Bone_Cortical_ICRU_44
/gate/boneBall2/vis/setColor white

/gate/waterBox/daughters/name boneBall3
/gate/waterBox/daughters/insert sphere
/gate/boneBall3/placement/setTranslation 0. 20 -25 mm
/gate/boneBall3/geometry/setRmin 0. mm
/gate/boneBall3/geometry/setRmax 5. mm
/gate/boneBall3/setMaterial Bone_Cortical_ICRU_44
/gate/boneBall3/vis/setColor white


################################
# Blood, Whole (ICRU-44) Balls #
################################
/gate/waterBox/daughters/name bloodBall1
/gate/waterBox/daughters/insert sphere
/gate/bloodBall1/placement/setTranslation 0. -20 -12.5 mm
/gate/bloodBall1/geometry/setRmin 0. mm
/gate/bloodBall1/geometry/setRmax 2. mm
/gate/bloodBall1/setMaterial Blood_Whole_ICRU_44
/gate/bloodBall1/vis/setColor yellow

/gate/waterBox/daughters/name bloodBall2
/gate/waterBox/daughters/insert sphere
/gate/bloodBall2/placement/setTranslation 0. 0. -12.5 mm
/gate/bloodBall2/geometry/setRmin 0. mm
/gate/bloodBall2/geometry/setRmax 3.5 mm
/gate/bloodBall2/setMaterial Blood_Whole_ICRU_44
/gate/bloodBall2/vis/setColor yellow

/gate/waterBox/daughters/name bloodBall3
/gate/waterBox/daughters/insert sphere
/gate/bloodBall3/placement/setTranslation 0. 20 -12.5 mm
/gate/bloodBall3/geometry/setRmin 0. mm
/gate/bloodBall3/geometry/setRmax 5. mm
/gate/bloodBall3/setMaterial Blood_Whole_ICRU_44
/gate/bloodBall3/vis/setColor yellow


############################################
# Brain, Grey/White Matter (ICRU-44) Balls #
############################################
/gate/waterBox/daughters/name brainBall1
/gate/waterBox/daughters/insert sphere
/gate/brainBall1/placement/setTranslation 0. -20 0. mm
/gate/brainBall1/geometry/setRmin 0. mm
/gate/brainBall1/geometry/setRmax 2. mm
/gate/brainBall1/setMaterial Brain_Grey_White_Matter_ICRU_44
/gate/brainBall1/vis/setColor red

/gate/waterBox/daughters/name brainBall2
/gate/waterBox/daughters/insert sphere
#/gate/brainBall2/placement/setTranslation 0. 0. 0. mm
/gate/brainBall2/geometry/setRmin 0. mm
/gate/brainBall2/geometry/setRmax 3.5 mm
/gate/brainBall2/setMaterial Brain_Grey_White_Matter_ICRU_44
/gate/brainBall2/vis/setColor red

/gate/waterBox/daughters/name brainBall3
/gate/waterBox/daughters/insert sphere
/gate/brainBall3/placement/setTranslation 0. 20 0. mm
/gate/brainBall3/geometry/setRmin 0. mm
/gate/brainBall3/geometry/setRmax 5. mm
/gate/brainBall3/setMaterial Brain_Grey_White_Matter_ICRU_44
/gate/brainBall3/vis/setColor red


#################################
# Breast Tissue (ICRU-44) Balls #
#################################
/gate/waterBox/daughters/name breastBall1
/gate/waterBox/daughters/insert sphere
/gate/breastBall1/placement/setTranslation 0. -20 12.5 mm
/gate/breastBall1/geometry/setRmin 0. mm
/gate/breastBall1/geometry/setRmax 2. mm
/gate/breastBall1/setMaterial Breast_Tissue_ICRU_44
/gate/breastBall1/vis/setColor blue

/gate/waterBox/daughters/name breastBall2
/gate/waterBox/daughters/insert sphere
/gate/breastBall2/placement/setTranslation 0. 0. 12.5 mm
/gate/breastBall2/geometry/setRmin 0. mm
/gate/breastBall2/geometry/setRmax 3.5 mm
/gate/breastBall2/setMaterial Breast_Tissue_ICRU_44
/gate/breastBall2/vis/setColor blue

/gate/waterBox/daughters/name breastBall3
/gate/waterBox/daughters/insert sphere
/gate/breastBall3/placement/setTranslation 0. 20 12.5 mm
/gate/breastBall3/geometry/setRmin 0. mm
/gate/breastBall3/geometry/setRmax 5. mm
/gate/breastBall3/setMaterial Breast_Tissue_ICRU_44
/gate/breastBall3/vis/setColor blue


##################################
# Adipose Tissue (ICRU-44) Balls #
##################################
/gate/waterBox/daughters/name adiposeBall1
/gate/waterBox/daughters/insert sphere
/gate/adiposeBall1/placement/setTranslation 0. -20 25 mm
/gate/adiposeBall1/geometry/setRmin 0. mm
/gate/adiposeBall1/geometry/setRmax 2. mm
/gate/adiposeBall1/setMaterial Adipose_Tissue_ICRU_44
/gate/adiposeBall1/vis/setColor cyan

/gate/waterBox/daughters/name adiposeBall2
/gate/waterBox/daughters/insert sphere
/gate/adiposeBall2/placement/setTranslation 0. 0. 25 mm
/gate/adiposeBall2/geometry/setRmin 0. mm
/gate/adiposeBall2/geometry/setRmax 3.5 mm
/gate/adiposeBall2/setMaterial Adipose_Tissue_ICRU_44
/gate/adiposeBall2/vis/setColor cyan

/gate/waterBox/daughters/name adiposeBall3
/gate/waterBox/daughters/insert sphere
/gate/adiposeBall3/placement/setTranslation 0. 20 25 mm
/gate/adiposeBall3/geometry/setRmin 0. mm
/gate/adiposeBall3/geometry/setRmax 5. mm
/gate/adiposeBall3/setMaterial Adipose_Tissue_ICRU_44
/gate/adiposeBall3/vis/setColor cyan
