/gate/source/addSource xraygun
/gate/source/verbose 0
/gate/source/xraygun/setActivity 350000. becquerel
/gate/source/xraygun/gps/verbose 0
/gate/source/xraygun/gps/particle gamma
/gate/source/xraygun/gps/energytype Arb
/gate/source/xraygun/gps/histname arb
/gate/source/xraygun/gps/emin 12.0 keV
/gate/source/xraygun/gps/emax 80.0 keV
/gate/source/xraygun/gps/histpoint 12.0 1
/gate/source/xraygun/gps/histpoint 12.5 9
/gate/source/xraygun/gps/histpoint 13.0 45
/gate/source/xraygun/gps/histpoint 13.5 172
/gate/source/xraygun/gps/histpoint 14.0 557
/gate/source/xraygun/gps/histpoint 14.5 1556
/gate/source/xraygun/gps/histpoint 15.0 3825
/gate/source/xraygun/gps/histpoint 15.5 8435
/gate/source/xraygun/gps/histpoint 16.0 16956
/gate/source/xraygun/gps/histpoint 16.5 31479
/gate/source/xraygun/gps/histpoint 17.0 54548
/gate/source/xraygun/gps/histpoint 17.5 88889
/gate/source/xraygun/gps/histpoint 18.0 137190
/gate/source/xraygun/gps/histpoint 18.5 202189
/gate/source/xraygun/gps/histpoint 19.0 286383
/gate/source/xraygun/gps/histpoint 19.5 391657
/gate/source/xraygun/gps/histpoint 20.0 518725
/gate/source/xraygun/gps/histpoint 20.5 667313
/gate/source/xraygun/gps/histpoint 21.0 837400
/gate/source/xraygun/gps/histpoint 21.5 1028592
/gate/source/xraygun/gps/histpoint 22.0 1238188
/gate/source/xraygun/gps/histpoint 22.5 1462686
/gate/source/xraygun/gps/histpoint 23.0 1700686
/gate/source/xraygun/gps/histpoint 23.5 1950869
/gate/source/xraygun/gps/histpoint 24.0 2210711
/gate/source/xraygun/gps/histpoint 24.5 2477621
/gate/source/xraygun/gps/histpoint 25.0 2747185
/gate/source/xraygun/gps/histpoint 25.5 3015067
/gate/source/xraygun/gps/histpoint 26.0 3280548
/gate/source/xraygun/gps/histpoint 26.5 3543291
/gate/source/xraygun/gps/histpoint 27.0 3801512
/gate/source/xraygun/gps/histpoint 27.5 4048735
/gate/source/xraygun/gps/histpoint 28.0 4281819
/gate/source/xraygun/gps/histpoint 28.5 4504426
/gate/source/xraygun/gps/histpoint 29.0 4717277
/gate/source/xraygun/gps/histpoint 29.5 4919691
/gate/source/xraygun/gps/histpoint 30.0 5107736
/gate/source/xraygun/gps/histpoint 30.5 5277794
/gate/source/xraygun/gps/histpoint 31.0 5433352
/gate/source/xraygun/gps/histpoint 31.5 5577627
/gate/source/xraygun/gps/histpoint 32.0 5710667
/gate/source/xraygun/gps/histpoint 32.5 5832628
/gate/source/xraygun/gps/histpoint 33.0 5943459
/gate/source/xraygun/gps/histpoint 33.5 6043450
/gate/source/xraygun/gps/histpoint 34.0 6132891
/gate/source/xraygun/gps/histpoint 34.5 6212000
/gate/source/xraygun/gps/histpoint 35.0 6277312
/gate/source/xraygun/gps/histpoint 35.5 6325549
/gate/source/xraygun/gps/histpoint 36.0 6361464
/gate/source/xraygun/gps/histpoint 36.5 6389524
/gate/source/xraygun/gps/histpoint 37.0 6409963
/gate/source/xraygun/gps/histpoint 37.5 6423179
/gate/source/xraygun/gps/histpoint 38.0 6429526
/gate/source/xraygun/gps/histpoint 38.5 6429323
/gate/source/xraygun/gps/histpoint 39.0 6423033
/gate/source/xraygun/gps/histpoint 39.5 6410890
/gate/source/xraygun/gps/histpoint 40.0 6390642
/gate/source/xraygun/gps/histpoint 40.5 6360319
/gate/source/xraygun/gps/histpoint 41.0 6323039
/gate/source/xraygun/gps/histpoint 41.5 6281903
/gate/source/xraygun/gps/histpoint 42.0 6237161
/gate/source/xraygun/gps/histpoint 42.5 6189038
/gate/source/xraygun/gps/histpoint 43.0 6137862
/gate/source/xraygun/gps/histpoint 43.5 6083634
/gate/source/xraygun/gps/histpoint 44.0 6026742
/gate/source/xraygun/gps/histpoint 44.5 5967431
/gate/source/xraygun/gps/histpoint 45.0 5903902
/gate/source/xraygun/gps/histpoint 45.5 5835066
/gate/source/xraygun/gps/histpoint 46.0 5762916
/gate/source/xraygun/gps/histpoint 46.5 5689277
/gate/source/xraygun/gps/histpoint 47.0 5614543
/gate/source/xraygun/gps/histpoint 47.5 5538508
/gate/source/xraygun/gps/histpoint 48.0 5461465
/gate/source/xraygun/gps/histpoint 48.5 5383633
/gate/source/xraygun/gps/histpoint 49.0 5304674
/gate/source/xraygun/gps/histpoint 49.5 5224979
/gate/source/xraygun/gps/histpoint 50.0 5143591
/gate/source/xraygun/gps/histpoint 50.5 5059589
/gate/source/xraygun/gps/histpoint 51.0 4974495
/gate/source/xraygun/gps/histpoint 51.5 4889057
/gate/source/xraygun/gps/histpoint 52.0 4803534
/gate/source/xraygun/gps/histpoint 52.5 4718134
/gate/source/xraygun/gps/histpoint 53.0 4632366
/gate/source/xraygun/gps/histpoint 53.5 4546624
/gate/source/xraygun/gps/histpoint 54.0 4460997
/gate/source/xraygun/gps/histpoint 54.5 4375202
/gate/source/xraygun/gps/histpoint 55.0 4288918
/gate/source/xraygun/gps/histpoint 55.5 4201513
/gate/source/xraygun/gps/histpoint 56.0 4113872
/gate/source/xraygun/gps/histpoint 56.5 4026756
/gate/source/xraygun/gps/histpoint 57.0 3939690
/gate/source/xraygun/gps/histpoint 57.5 5060742
/gate/source/xraygun/gps/histpoint 58.0 4974371
/gate/source/xraygun/gps/histpoint 58.5 3680322
/gate/source/xraygun/gps/histpoint 59.0 5751494
/gate/source/xraygun/gps/histpoint 59.5 5665939
/gate/source/xraygun/gps/histpoint 60.0 3423306
/gate/source/xraygun/gps/histpoint 60.5 3337495
/gate/source/xraygun/gps/histpoint 61.0 3251563
/gate/source/xraygun/gps/histpoint 61.5 3166000
/gate/source/xraygun/gps/histpoint 62.0 3080853
/gate/source/xraygun/gps/histpoint 62.5 2995917
/gate/source/xraygun/gps/histpoint 63.0 2911390
/gate/source/xraygun/gps/histpoint 63.5 2827096
/gate/source/xraygun/gps/histpoint 64.0 2743027
/gate/source/xraygun/gps/histpoint 64.5 2659312
/gate/source/xraygun/gps/histpoint 65.0 2575313
/gate/source/xraygun/gps/histpoint 65.5 2491233
/gate/source/xraygun/gps/histpoint 66.0 2407437
/gate/source/xraygun/gps/histpoint 66.5 2586573
/gate/source/xraygun/gps/histpoint 67.0 3013655
/gate/source/xraygun/gps/histpoint 67.5 2680453
/gate/source/xraygun/gps/histpoint 68.0 2086699
/gate/source/xraygun/gps/histpoint 68.5 1990699
/gate/source/xraygun/gps/histpoint 69.0 2092263
/gate/source/xraygun/gps/histpoint 69.5 1991900
/gate/source/xraygun/gps/histpoint 70.0 1680084
/gate/source/xraygun/gps/histpoint 70.5 1573588
/gate/source/xraygun/gps/histpoint 71.0 1497392
/gate/source/xraygun/gps/histpoint 71.5 1420837
/gate/source/xraygun/gps/histpoint 72.0 1343888
/gate/source/xraygun/gps/histpoint 72.5 1266725
/gate/source/xraygun/gps/histpoint 73.0 1188958
/gate/source/xraygun/gps/histpoint 73.5 1110755
/gate/source/xraygun/gps/histpoint 74.0 1032133
/gate/source/xraygun/gps/histpoint 74.5 952716
/gate/source/xraygun/gps/histpoint 75.0 872847
/gate/source/xraygun/gps/histpoint 75.5 792269
/gate/source/xraygun/gps/histpoint 76.0 710751
/gate/source/xraygun/gps/histpoint 76.5 628579
/gate/source/xraygun/gps/histpoint 77.0 545354
/gate/source/xraygun/gps/histpoint 77.5 461219
/gate/source/xraygun/gps/histpoint 78.0 376193
/gate/source/xraygun/gps/histpoint 78.5 290386
/gate/source/xraygun/gps/histpoint 79.0 203648
/gate/source/xraygun/gps/histpoint 79.5 109683
/gate/source/xraygun/gps/histpoint 80.0 29755
/gate/source/xraygun/gps/arbint Lin
/gate/source/xraygun/gps/type Plane
/gate/source/xraygun/gps/shape Point
/gate/source/xraygun/gps/centre 400. 0. 0. mm
/gate/source/xraygun/gps/angtype iso
/gate/source/list


#/gate/source/xraygun/gps/arbint Lin
#/gate/source/xraygun/gps/type Plane
#/gate/source/xraygun/gps/shape Rectangle
/gate/source/xraygun/gps/type Point
/gate/source/xraygun/gps/direction 0 0 1
/gate/source/xraygun/gps/centre 0. 0. -10.0 cm
/gate/source/xraygun/gps/angtype iso
/gate/source/list
